# These are example options for a hub node that is part of a cluster
# Docker-compose and this file is not required for a single-hub installation.
version: '2'
services:
  hub:
    build: .
    command: 1g 2g 100m
    volumes:
      - /log:/mnt/log:rw
      - /spoke:/mnt/spoke:rw
      - /etc/hub:/etc/hub:ro
    network_mode: "host"
    logging:
      driver: json-file
      options:
        max-size: "2g"
        max-file: "2"
